### ISSUE TITLE
Receiving an error while using the generator?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [ID25/rails_emoji_picker#1]
I've added the includes and followed your steps. But, I am getting an error for the asset_host method. 

/config/initializers/emoji.rb:1:in `<top (required)>': undefined method `asset_host=' for Emoji:Module (NoMethodError)

emoji.rb

Emoji.asset_host = 'emoji.cdn.com'
Emoji.asset_path = '/assets/emoji'
Emoji.use_plaintext_alt_tags = true

All three methods are considered undefined (NoMethodError). I'm using Windows 10 btw.

**Comment by ID25** [comment]
Fixed in 0.1.5
