### ISSUE TITLE
Is there any way to retrieve "alt" value on submit form

### ISSUE THREAD

**Issue by curbsaleem** [ID25/rails_emoji_picker#3]
Hi

I am using rails_emoji_picker in my app. when we click on any emoji.
it render following html in text area.

`<img src="/assets/emoji//blank.gif" class="img" style="display:inline-block;width:25px;height:25px;background:url('/assets/emoji//emoji_spritesheet_0.png') -75px 0px no-repeat;background-size:675px 175px;" alt=":blush:">`

when i submit the form i want to receive values as ": blush :" rather than "symbol "

is thr any way to do that?

Thanks

**Comment by ID25** [comment]
Fixed in 0.1.5

**Comment by ID25** [comment]
Fixed in 0.1.5
