### ISSUE TITLE
production mode icon path issue

### ISSUE THREAD

**Issue by curbsaleem** [ID25/rails_emoji_picker#5]
Hi

I am facing issue of path of icon in production mode. Any one know how i can fix this?

assets.rb file has following lines

`Rails.application.config.assets.precompile += %w(emoji/*.png)
Rails.application.config.assets.paths << Emoji.images_path`

logs
Started GET "/emoji_img//blank.gif" 
Started GET "/images/emoji/unicode/1f600.png" 

Thanks

**Comment by ID25** [comment]
Fixed in 0.1.5
