### ISSUE TITLE
Can't retrieve icon for :heart: , :relaxed: and some others emo

### ISSUE THREAD

**Issue by sahidulislam** [ID25/rails_emoji_picker#6]
Hi,
I can save data successfully with emo but when I going to show text with emo, I can't. 
It says **undefined method `name' for nil:NilClass**
May be it occurred in this line 
`c.gsub!(regex, emoji_name(Emoji.find_by_unicode(emoji).name)) if emoji.present? `
in emoji_helper.rb

It occurred for a few number of emo's like :hearth:, :relaxed : nd so on.

Thanks,
Sahid

**Comment by ID25** [comment]
Fixed in 0.1.5
